language: elixir
elixir:
  - 1.3.4
  - 1.4.0
otp_release:
  - 18.3
  - 19.2

sudo: false

script: "MIX_ENV=test mix do deps.get, test"

after_success:
	- "mix compile"
	- "mix coveralls.travis"
  - "mix deps.get --only docs"
  - "MIX_ENV=docs mix inch.report"
  
after_failure:
	- "mix compile"
	- "mix coveralls.travis"
  
